spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  #JPA 설정
  jpa:
    properties:
      hibernate:
        # show_sql : 실행되는 쿼리를 콘솔에 출력하는 역할
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: update

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace